backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor

media_folder: static/img
public_folder: /img

display_url: https://www.lenaruppert.de
# TODO add backend logo
logo_url: https://www.lenaruppert.de/static/logo-b8b6795b2bfdaef686f9840bdf28f96e.png

pages_fields: &pages_fields
  fields:
    - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "standard",
      }
    - { label: "Titel", name: "title", widget: "string" }
    - { label: "Text", name: "body", widget: "markdown" }

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/404/index.md"
        label: "404"
        name: "404"
        <<: *pages_fields
      - file: "src/pages/agb/index.md"
        label: "AGB"
        name: "agb"
        <<: *pages_fields
      - file: "src/pages/datenschutz/index.md"
        label: "Datenschutz"
        name: "datenschutz"
        <<: *pages_fields
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        <<: *pages_fields
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        <<: *pages_fields
      - file: "src/pages/referenzen/index.md"
        label: "Referenzen"
        name: "referenzen"
        <<: *pages_fields
      - file: "src/pages/start/index.md"
        label: "Start"
        name: "start"
        <<: *pages_fields
      - file: "src/pages/ueber-mich/index.md"
        label: "Über mich"
        name: "ueber-mich"
        <<: *pages_fields
  - name: "samples"
    label: "Textproben"
    folder: "src-pages/textproben"
    create: true
    fields:
      - {
        label: "Template Key",
        name: "templateKey",
        widget: "hidden",
        default: "standard",
      }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subTitle", widget: "string" }
      - { label: "Reihenfolge", name: "order", widget: "number" }
      - { label: "Link", name: "uri", widget: "string" }
      - { label: "Text", name: "body", widget: "markdown" }
