backend:
  name: github
  repo: ruppertdesign/lenaruppert.de
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/ueber-mich/index.md"
        label: "Über mich"
        name: "ueber-mich"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}